#!/usr/bin/python3
# sep 20, 2026
#question5
"""program to find the roots of a quadratic equation. Figure out what the inputs
should be and also have provision to deal with cases where you end up getting complex
roots."""
"""X=(-b+sqrt(b**2)-(4*a*c))/(2*a)"""

import math

a=float(input("Enter a: "))
b=float(input("Enter b: "))
c=float(input("Enter c: "))

"""Negative (Discriminant < 0) : Two complex/imaginary root
Positive (Discriminant > 0) : Two distinct real roots
Zero (Discriminant = 0) : One repeated real root
x=Discriminant"""
x=((b**2)-(4*a*c))

if x<0 :
    print("This equation has no real roots.")
elif x==0 :
    root=((-b)/(2*a))
    print(f'The root is : {root}')
else :
    root1 = (-b + math.sqrt(x))/(2*a)
    root2 = (-b - math.sqrt(x))/(2*a)
    print(root1 , root2)
