#!/usr/bin/python3
# sep 20, 2026
#question8
"""program to tell which quadrat a given point lies in the first, second, third or fourth quadrant"""

a=float(input("x:"))
b=float(input("y:"))

if a>0 and b>0:
    print("The point lies in the first quadrant.")
elif a>0 and b<0:
    print("The point lies in the second quadrant.")
elif a<0 and b<0:
    print("The point lies in the third quadrant.")
elif a<0 and b>0:
    print("The point lies in the fourth quadrant.")
else:
    print("The point lies at the origin")
