#!/usr/bin/python3
# sep 20, 2026
#question6
"""program to print the sum of the digits in a number."""
"""modulus anf integer division{%,//]"""

import array
a=int(input("Enter a number:"))
sum=0
while a>0:
    sum=(sum+(a%10))
    a=(a//10)
print(f'The sum of the digits are: {sum}')
