#!/usr/bin/python3
# sep 20, 2026
#question13
"""program to print the factorial of a number"""

a=int(input("Enter a number:"))
c=a
b=1
if a>0:
    while a>0 :
        b=(b*a)
        a=(a-1)
    print(f'{a}={b}')
else:
    print("ERROR:Negative numbers do not have a standard factorial value")
